-- Seed catalog for JVM/backend roles. Generated from a compact definition; the
-- normalized_alias values follow the same rule as SkillNormalizer.kt, and
-- SkillCatalogSeedTest asserts the two never drift apart.

insert into canonical_skill (name, category) values
    ('Kotlin', 'LANGUAGE'),
    ('Java', 'LANGUAGE'),
    ('Groovy', 'LANGUAGE'),
    ('Scala', 'LANGUAGE'),
    ('Clojure', 'LANGUAGE'),
    ('Python', 'LANGUAGE'),
    ('JavaScript', 'LANGUAGE'),
    ('TypeScript', 'LANGUAGE'),
    ('Go', 'LANGUAGE'),
    ('Rust', 'LANGUAGE'),
    ('C', 'LANGUAGE'),
    ('C++', 'LANGUAGE'),
    ('C#', 'LANGUAGE'),
    ('Ruby', 'LANGUAGE'),
    ('PHP', 'LANGUAGE'),
    ('Swift', 'LANGUAGE'),
    ('SQL', 'LANGUAGE'),
    ('Bash', 'LANGUAGE'),
    ('JVM', 'LANGUAGE'),
    ('Spring', 'FRAMEWORK'),
    ('Spring Boot', 'FRAMEWORK'),
    ('Spring Security', 'FRAMEWORK'),
    ('Spring Data', 'FRAMEWORK'),
    ('Spring Batch', 'FRAMEWORK'),
    ('Spring Cloud', 'FRAMEWORK'),
    ('Spring WebFlux', 'FRAMEWORK'),
    ('Spring MVC', 'FRAMEWORK'),
    ('Spring Modulith', 'FRAMEWORK'),
    ('Spring AI', 'FRAMEWORK'),
    ('Quarkus', 'FRAMEWORK'),
    ('Micronaut', 'FRAMEWORK'),
    ('Jakarta EE', 'FRAMEWORK'),
    ('Hibernate', 'FRAMEWORK'),
    ('JPA', 'FRAMEWORK'),
    ('jOOQ', 'FRAMEWORK'),
    ('MyBatis', 'FRAMEWORK'),
    ('Ktor', 'FRAMEWORK'),
    ('Vert.x', 'FRAMEWORK'),
    ('Micrometer', 'FRAMEWORK'),
    ('Thymeleaf', 'FRAMEWORK'),
    ('Django', 'FRAMEWORK'),
    ('Flask', 'FRAMEWORK'),
    ('FastAPI', 'FRAMEWORK'),
    ('Express.js', 'FRAMEWORK'),
    ('NestJS', 'FRAMEWORK'),
    ('Ruby on Rails', 'FRAMEWORK'),
    ('Laravel', 'FRAMEWORK'),
    ('ASP.NET', 'FRAMEWORK'),
    ('Node.js', 'FRAMEWORK'),
    ('React', 'FRONTEND'),
    ('Angular', 'FRONTEND'),
    ('Vue.js', 'FRONTEND'),
    ('Svelte', 'FRONTEND'),
    ('Next.js', 'FRONTEND'),
    ('Astro', 'FRONTEND'),
    ('HTML', 'FRONTEND'),
    ('CSS', 'FRONTEND'),
    ('Sass', 'FRONTEND'),
    ('Tailwind CSS', 'FRONTEND'),
    ('Redux', 'FRONTEND'),
    ('Webpack', 'FRONTEND'),
    ('Vite', 'FRONTEND'),
    ('jQuery', 'FRONTEND'),
    ('PostgreSQL', 'DATABASE'),
    ('MySQL', 'DATABASE'),
    ('MariaDB', 'DATABASE'),
    ('Oracle Database', 'DATABASE'),
    ('SQL Server', 'DATABASE'),
    ('MongoDB', 'DATABASE'),
    ('Redis', 'DATABASE'),
    ('Apache Cassandra', 'DATABASE'),
    ('Elasticsearch', 'DATABASE'),
    ('DynamoDB', 'DATABASE'),
    ('Neo4j', 'DATABASE'),
    ('SQLite', 'DATABASE'),
    ('H2', 'DATABASE'),
    ('ClickHouse', 'DATABASE'),
    ('Liquibase', 'DATABASE'),
    ('Flyway', 'DATABASE'),
    ('pgvector', 'DATABASE'),
    ('Database Design', 'DATABASE'),
    ('Data Modeling', 'DATABASE'),
    ('Apache Kafka', 'MESSAGING'),
    ('RabbitMQ', 'MESSAGING'),
    ('ActiveMQ', 'MESSAGING'),
    ('Amazon SQS', 'MESSAGING'),
    ('Apache Pulsar', 'MESSAGING'),
    ('gRPC', 'MESSAGING'),
    ('GraphQL', 'MESSAGING'),
    ('REST', 'MESSAGING'),
    ('WebSocket', 'MESSAGING'),
    ('Server-Sent Events', 'MESSAGING'),
    ('Apache Avro', 'MESSAGING'),
    ('Protocol Buffers', 'MESSAGING'),
    ('AWS', 'CLOUD'),
    ('Microsoft Azure', 'CLOUD'),
    ('Google Cloud Platform', 'CLOUD'),
    ('AWS Lambda', 'CLOUD'),
    ('Amazon S3', 'CLOUD'),
    ('Amazon EC2', 'CLOUD'),
    ('Amazon RDS', 'CLOUD'),
    ('Azure Functions', 'CLOUD'),
    ('Cloudflare', 'CLOUD'),
    ('Heroku', 'CLOUD'),
    ('Vercel', 'CLOUD'),
    ('Neon', 'CLOUD'),
    ('Firebase', 'CLOUD'),
    ('Serverless', 'CLOUD'),
    ('Docker', 'DEVOPS'),
    ('Kubernetes', 'DEVOPS'),
    ('Helm', 'DEVOPS'),
    ('Terraform', 'DEVOPS'),
    ('Ansible', 'DEVOPS'),
    ('Jenkins', 'DEVOPS'),
    ('GitHub Actions', 'DEVOPS'),
    ('GitLab CI', 'DEVOPS'),
    ('ArgoCD', 'DEVOPS'),
    ('Prometheus', 'DEVOPS'),
    ('Grafana', 'DEVOPS'),
    ('Datadog', 'DEVOPS'),
    ('OpenTelemetry', 'DEVOPS'),
    ('ELK Stack', 'DEVOPS'),
    ('Nginx', 'DEVOPS'),
    ('Linux', 'DEVOPS'),
    ('Git', 'DEVOPS'),
    ('Maven', 'DEVOPS'),
    ('Gradle', 'DEVOPS'),
    ('CI/CD', 'DEVOPS'),
    ('Istio', 'DEVOPS'),
    ('HashiCorp Vault', 'DEVOPS'),
    ('JUnit', 'TESTING'),
    ('Kotest', 'TESTING'),
    ('Mockito', 'TESTING'),
    ('MockK', 'TESTING'),
    ('Testcontainers', 'TESTING'),
    ('AssertJ', 'TESTING'),
    ('Selenium', 'TESTING'),
    ('Playwright', 'TESTING'),
    ('Cypress', 'TESTING'),
    ('Cucumber', 'TESTING'),
    ('WireMock', 'TESTING'),
    ('JMeter', 'TESTING'),
    ('Gatling', 'TESTING'),
    ('Test-Driven Development', 'TESTING'),
    ('Unit Testing', 'TESTING'),
    ('Integration Testing', 'TESTING'),
    ('Contract Testing', 'TESTING'),
    ('LangChain', 'AI'),
    ('LangChain4j', 'AI'),
    ('OpenAI API', 'AI'),
    ('Retrieval-Augmented Generation', 'AI'),
    ('Vector Databases', 'AI'),
    ('Prompt Engineering', 'AI'),
    ('Large Language Models', 'AI'),
    ('Machine Learning', 'AI'),
    ('TensorFlow', 'AI'),
    ('PyTorch', 'AI'),
    ('Hugging Face', 'AI'),
    ('Ollama', 'AI'),
    ('Model Context Protocol', 'AI'),
    ('Microservices', 'PRACTICE'),
    ('Event-Driven Architecture', 'PRACTICE'),
    ('Domain-Driven Design', 'PRACTICE'),
    ('Hexagonal Architecture', 'PRACTICE'),
    ('CQRS', 'PRACTICE'),
    ('Event Sourcing', 'PRACTICE'),
    ('API Design', 'PRACTICE'),
    ('Agile', 'PRACTICE'),
    ('Scrum', 'PRACTICE'),
    ('Kanban', 'PRACTICE'),
    ('Code Review', 'PRACTICE'),
    ('Pair Programming', 'PRACTICE'),
    ('Clean Code', 'PRACTICE'),
    ('SOLID', 'PRACTICE'),
    ('Design Patterns', 'PRACTICE'),
    ('Refactoring', 'PRACTICE'),
    ('Distributed Systems', 'PRACTICE'),
    ('Concurrency', 'PRACTICE'),
    ('Kotlin Coroutines', 'PRACTICE'),
    ('Reactive Programming', 'PRACTICE'),
    ('Functional Programming', 'PRACTICE'),
    ('Object-Oriented Programming', 'PRACTICE'),
    ('Performance Tuning', 'PRACTICE'),
    ('Application Security', 'PRACTICE'),
    ('OAuth 2.0', 'PRACTICE'),
    ('OpenID Connect', 'PRACTICE'),
    ('JWT', 'PRACTICE'),
    ('Observability', 'PRACTICE'),
    ('Caching', 'PRACTICE'),
    ('API Gateway', 'PRACTICE'),
    ('Load Balancing', 'PRACTICE'),
    ('Scalability', 'PRACTICE'),
    ('Monolith', 'PRACTICE'),
    ('Technical Documentation', 'PRACTICE'),
    ('IntelliJ IDEA', 'TOOL'),
    ('Visual Studio Code', 'TOOL'),
    ('Jira', 'TOOL'),
    ('Confluence', 'TOOL'),
    ('Postman', 'TOOL'),
    ('OpenAPI', 'TOOL'),
    ('Figma', 'TOOL'),
    ('Communication', 'SOFT'),
    ('Teamwork', 'SOFT'),
    ('Mentoring', 'SOFT'),
    ('Leadership', 'SOFT'),
    ('Problem Solving', 'SOFT'),
    ('Ownership', 'SOFT'),
    ('Stakeholder Management', 'SOFT'),
    ('Time Management', 'SOFT'),
    ('Adaptability', 'SOFT');

insert into skill_alias (canonical_skill_id, alias, normalized_alias)
select cs.id, v.alias, v.normalized_alias
from (values
    ('Kotlin', 'Kotlin', 'kotlin'),
    ('Java', 'Java', 'java'),
    ('Java', 'Java SE', 'javase'),
    ('Java', 'Core Java', 'corejava'),
    ('Groovy', 'Groovy', 'groovy'),
    ('Scala', 'Scala', 'scala'),
    ('Clojure', 'Clojure', 'clojure'),
    ('Python', 'Python', 'python'),
    ('Python', 'Python 3', 'python3'),
    ('JavaScript', 'JavaScript', 'javascript'),
    ('JavaScript', 'JS', 'js'),
    ('JavaScript', 'ECMAScript', 'ecmascript'),
    ('JavaScript', 'ES6', 'es6'),
    ('TypeScript', 'TypeScript', 'typescript'),
    ('TypeScript', 'TS', 'ts'),
    ('Go', 'Go', 'go'),
    ('Go', 'Golang', 'golang'),
    ('Rust', 'Rust', 'rust'),
    ('C', 'C', 'c'),
    ('C++', 'C++', 'cpp'),
    ('C#', 'C#', 'csharp'),
    ('Ruby', 'Ruby', 'ruby'),
    ('PHP', 'PHP', 'php'),
    ('Swift', 'Swift', 'swift'),
    ('SQL', 'SQL', 'sql'),
    ('SQL', 'Structured Query Language', 'structuredquerylanguage'),
    ('Bash', 'Bash', 'bash'),
    ('Bash', 'Shell', 'shell'),
    ('Bash', 'Shell Scripting', 'shellscripting'),
    ('Bash', 'Zsh', 'zsh'),
    ('JVM', 'JVM', 'jvm'),
    ('JVM', 'Java Virtual Machine', 'javavirtualmachine'),
    ('Spring', 'Spring', 'spring'),
    ('Spring', 'Spring Framework', 'springframework'),
    ('Spring Boot', 'Spring Boot', 'springboot'),
    ('Spring Security', 'Spring Security', 'springsecurity'),
    ('Spring Data', 'Spring Data', 'springdata'),
    ('Spring Data', 'Spring Data JPA', 'springdatajpa'),
    ('Spring Data', 'Spring Data JDBC', 'springdatajdbc'),
    ('Spring Batch', 'Spring Batch', 'springbatch'),
    ('Spring Cloud', 'Spring Cloud', 'springcloud'),
    ('Spring WebFlux', 'Spring WebFlux', 'springwebflux'),
    ('Spring WebFlux', 'WebFlux', 'webflux'),
    ('Spring MVC', 'Spring MVC', 'springmvc'),
    ('Spring MVC', 'WebMVC', 'webmvc'),
    ('Spring Modulith', 'Spring Modulith', 'springmodulith'),
    ('Spring AI', 'Spring AI', 'springai'),
    ('Quarkus', 'Quarkus', 'quarkus'),
    ('Micronaut', 'Micronaut', 'micronaut'),
    ('Jakarta EE', 'Jakarta EE', 'jakartaee'),
    ('Jakarta EE', 'Java EE', 'javaee'),
    ('Jakarta EE', 'J2EE', 'j2ee'),
    ('Hibernate', 'Hibernate', 'hibernate'),
    ('JPA', 'JPA', 'jpa'),
    ('JPA', 'Java Persistence API', 'javapersistenceapi'),
    ('jOOQ', 'jOOQ', 'jooq'),
    ('MyBatis', 'MyBatis', 'mybatis'),
    ('Ktor', 'Ktor', 'ktor'),
    ('Vert.x', 'Vert.x', 'vertx'),
    ('Vert.x', 'Eclipse Vertx', 'eclipsevertx'),
    ('Micrometer', 'Micrometer', 'micrometer'),
    ('Thymeleaf', 'Thymeleaf', 'thymeleaf'),
    ('Django', 'Django', 'django'),
    ('Flask', 'Flask', 'flask'),
    ('FastAPI', 'FastAPI', 'fastapi'),
    ('Express.js', 'Express.js', 'expressjs'),
    ('Express.js', 'Express', 'express'),
    ('NestJS', 'NestJS', 'nestjs'),
    ('Ruby on Rails', 'Ruby on Rails', 'rubyonrails'),
    ('Ruby on Rails', 'Rails', 'rails'),
    ('Laravel', 'Laravel', 'laravel'),
    ('ASP.NET', 'ASP.NET', 'aspnet'),
    ('ASP.NET', 'ASP.NET Core', 'aspnetcore'),
    ('ASP.NET', '.NET', 'net'),
    ('Node.js', 'Node.js', 'nodejs'),
    ('Node.js', 'Node', 'node'),
    ('React', 'React', 'react'),
    ('React', 'React.js', 'reactjs'),
    ('Angular', 'Angular', 'angular'),
    ('Angular', 'AngularJS', 'angularjs'),
    ('Angular', 'Angular 2+', 'angular2p'),
    ('Vue.js', 'Vue.js', 'vuejs'),
    ('Vue.js', 'Vue', 'vue'),
    ('Svelte', 'Svelte', 'svelte'),
    ('Svelte', 'SvelteKit', 'sveltekit'),
    ('Next.js', 'Next.js', 'nextjs'),
    ('Astro', 'Astro', 'astro'),
    ('Astro', 'Astro Framework', 'astroframework'),
    ('HTML', 'HTML', 'html'),
    ('HTML', 'HTML5', 'html5'),
    ('CSS', 'CSS', 'css'),
    ('CSS', 'CSS3', 'css3'),
    ('Sass', 'Sass', 'sass'),
    ('Sass', 'SCSS', 'scss'),
    ('Tailwind CSS', 'Tailwind CSS', 'tailwindcss'),
    ('Tailwind CSS', 'Tailwind', 'tailwind'),
    ('Redux', 'Redux', 'redux'),
    ('Webpack', 'Webpack', 'webpack'),
    ('Vite', 'Vite', 'vite'),
    ('jQuery', 'jQuery', 'jquery'),
    ('PostgreSQL', 'PostgreSQL', 'postgresql'),
    ('PostgreSQL', 'Postgres', 'postgres'),
    ('PostgreSQL', 'psql', 'psql'),
    ('MySQL', 'MySQL', 'mysql'),
    ('MariaDB', 'MariaDB', 'mariadb'),
    ('Oracle Database', 'Oracle Database', 'oracledatabase'),
    ('Oracle Database', 'Oracle DB', 'oracledb'),
    ('Oracle Database', 'OracleSQL', 'oraclesql'),
    ('Oracle Database', 'PL/SQL', 'plsql'),
    ('SQL Server', 'SQL Server', 'sqlserver'),
    ('SQL Server', 'MSSQL', 'mssql'),
    ('SQL Server', 'Microsoft SQL Server', 'microsoftsqlserver'),
    ('SQL Server', 'T-SQL', 'tsql'),
    ('MongoDB', 'MongoDB', 'mongodb'),
    ('MongoDB', 'Mongo', 'mongo'),
    ('Redis', 'Redis', 'redis'),
    ('Apache Cassandra', 'Apache Cassandra', 'apachecassandra'),
    ('Apache Cassandra', 'Cassandra', 'cassandra'),
    ('Elasticsearch', 'Elasticsearch', 'elasticsearch'),
    ('Elasticsearch', 'OpenSearch', 'opensearch'),
    ('DynamoDB', 'DynamoDB', 'dynamodb'),
    ('DynamoDB', 'Amazon DynamoDB', 'amazondynamodb'),
    ('Neo4j', 'Neo4j', 'neo4j'),
    ('SQLite', 'SQLite', 'sqlite'),
    ('H2', 'H2', 'h2'),
    ('H2', 'H2 Database', 'h2database'),
    ('ClickHouse', 'ClickHouse', 'clickhouse'),
    ('Liquibase', 'Liquibase', 'liquibase'),
    ('Flyway', 'Flyway', 'flyway'),
    ('pgvector', 'pgvector', 'pgvector'),
    ('Database Design', 'Database Design', 'databasedesign'),
    ('Database Design', 'Schema Design', 'schemadesign'),
    ('Data Modeling', 'Data Modeling', 'datamodeling'),
    ('Data Modeling', 'Data Modelling', 'datamodelling'),
    ('Apache Kafka', 'Apache Kafka', 'apachekafka'),
    ('Apache Kafka', 'Kafka', 'kafka'),
    ('RabbitMQ', 'RabbitMQ', 'rabbitmq'),
    ('ActiveMQ', 'ActiveMQ', 'activemq'),
    ('Amazon SQS', 'Amazon SQS', 'amazonsqs'),
    ('Amazon SQS', 'SQS', 'sqs'),
    ('Apache Pulsar', 'Apache Pulsar', 'apachepulsar'),
    ('Apache Pulsar', 'Pulsar', 'pulsar'),
    ('gRPC', 'gRPC', 'grpc'),
    ('GraphQL', 'GraphQL', 'graphql'),
    ('REST', 'REST', 'rest'),
    ('REST', 'RESTful', 'restful'),
    ('REST', 'REST API', 'restapi'),
    ('REST', 'RESTful API', 'restfulapi'),
    ('WebSocket', 'WebSocket', 'websocket'),
    ('WebSocket', 'WebSockets', 'websockets'),
    ('Server-Sent Events', 'Server-Sent Events', 'serversentevents'),
    ('Server-Sent Events', 'SSE', 'sse'),
    ('Apache Avro', 'Apache Avro', 'apacheavro'),
    ('Apache Avro', 'Avro', 'avro'),
    ('Protocol Buffers', 'Protocol Buffers', 'protocolbuffers'),
    ('Protocol Buffers', 'Protobuf', 'protobuf'),
    ('AWS', 'AWS', 'aws'),
    ('AWS', 'Amazon Web Services', 'amazonwebservices'),
    ('Microsoft Azure', 'Microsoft Azure', 'microsoftazure'),
    ('Microsoft Azure', 'Azure', 'azure'),
    ('Google Cloud Platform', 'Google Cloud Platform', 'googlecloudplatform'),
    ('Google Cloud Platform', 'GCP', 'gcp'),
    ('Google Cloud Platform', 'Google Cloud', 'googlecloud'),
    ('AWS Lambda', 'AWS Lambda', 'awslambda'),
    ('AWS Lambda', 'Lambda', 'lambda'),
    ('Amazon S3', 'Amazon S3', 'amazons3'),
    ('Amazon S3', 'S3', 's3'),
    ('Amazon EC2', 'Amazon EC2', 'amazonec2'),
    ('Amazon EC2', 'EC2', 'ec2'),
    ('Amazon RDS', 'Amazon RDS', 'amazonrds'),
    ('Amazon RDS', 'RDS', 'rds'),
    ('Azure Functions', 'Azure Functions', 'azurefunctions'),
    ('Cloudflare', 'Cloudflare', 'cloudflare'),
    ('Heroku', 'Heroku', 'heroku'),
    ('Vercel', 'Vercel', 'vercel'),
    ('Neon', 'Neon', 'neon'),
    ('Neon', 'Neon Postgres', 'neonpostgres'),
    ('Firebase', 'Firebase', 'firebase'),
    ('Serverless', 'Serverless', 'serverless'),
    ('Docker', 'Docker', 'docker'),
    ('Docker', 'Containers', 'containers'),
    ('Docker', 'Containerization', 'containerization'),
    ('Kubernetes', 'Kubernetes', 'kubernetes'),
    ('Kubernetes', 'K8s', 'k8s'),
    ('Kubernetes', 'Container Orchestration', 'containerorchestration'),
    ('Helm', 'Helm', 'helm'),
    ('Terraform', 'Terraform', 'terraform'),
    ('Terraform', 'OpenTofu', 'opentofu'),
    ('Ansible', 'Ansible', 'ansible'),
    ('Jenkins', 'Jenkins', 'jenkins'),
    ('GitHub Actions', 'GitHub Actions', 'githubactions'),
    ('GitLab CI', 'GitLab CI', 'gitlabci'),
    ('GitLab CI', 'GitLab CI/CD', 'gitlabcicd'),
    ('ArgoCD', 'ArgoCD', 'argocd'),
    ('Prometheus', 'Prometheus', 'prometheus'),
    ('Grafana', 'Grafana', 'grafana'),
    ('Datadog', 'Datadog', 'datadog'),
    ('OpenTelemetry', 'OpenTelemetry', 'opentelemetry'),
    ('OpenTelemetry', 'OTel', 'otel'),
    ('ELK Stack', 'ELK Stack', 'elkstack'),
    ('ELK Stack', 'ELK', 'elk'),
    ('ELK Stack', 'Logstash', 'logstash'),
    ('ELK Stack', 'Kibana', 'kibana'),
    ('Nginx', 'Nginx', 'nginx'),
    ('Linux', 'Linux', 'linux'),
    ('Linux', 'Unix', 'unix'),
    ('Git', 'Git', 'git'),
    ('Maven', 'Maven', 'maven'),
    ('Maven', 'Apache Maven', 'apachemaven'),
    ('Gradle', 'Gradle', 'gradle'),
    ('CI/CD', 'CI/CD', 'cicd'),
    ('CI/CD', 'Continuous Integration', 'continuousintegration'),
    ('CI/CD', 'Continuous Delivery', 'continuousdelivery'),
    ('CI/CD', 'Continuous Deployment', 'continuousdeployment'),
    ('Istio', 'Istio', 'istio'),
    ('Istio', 'Service Mesh', 'servicemesh'),
    ('HashiCorp Vault', 'HashiCorp Vault', 'hashicorpvault'),
    ('HashiCorp Vault', 'Vault', 'vault'),
    ('JUnit', 'JUnit', 'junit'),
    ('JUnit', 'JUnit 5', 'junit5'),
    ('JUnit', 'Jupiter', 'jupiter'),
    ('Kotest', 'Kotest', 'kotest'),
    ('Mockito', 'Mockito', 'mockito'),
    ('MockK', 'MockK', 'mockk'),
    ('Testcontainers', 'Testcontainers', 'testcontainers'),
    ('AssertJ', 'AssertJ', 'assertj'),
    ('Selenium', 'Selenium', 'selenium'),
    ('Playwright', 'Playwright', 'playwright'),
    ('Cypress', 'Cypress', 'cypress'),
    ('Cucumber', 'Cucumber', 'cucumber'),
    ('Cucumber', 'Gherkin', 'gherkin'),
    ('Cucumber', 'BDD', 'bdd'),
    ('WireMock', 'WireMock', 'wiremock'),
    ('JMeter', 'JMeter', 'jmeter'),
    ('Gatling', 'Gatling', 'gatling'),
    ('Test-Driven Development', 'Test-Driven Development', 'testdrivendevelopment'),
    ('Test-Driven Development', 'TDD', 'tdd'),
    ('Unit Testing', 'Unit Testing', 'unittesting'),
    ('Unit Testing', 'Unit Tests', 'unittests'),
    ('Integration Testing', 'Integration Testing', 'integrationtesting'),
    ('Integration Testing', 'Integration Tests', 'integrationtests'),
    ('Contract Testing', 'Contract Testing', 'contracttesting'),
    ('Contract Testing', 'Pact', 'pact'),
    ('LangChain', 'LangChain', 'langchain'),
    ('LangChain4j', 'LangChain4j', 'langchain4j'),
    ('OpenAI API', 'OpenAI API', 'openaiapi'),
    ('OpenAI API', 'OpenAI', 'openai'),
    ('Retrieval-Augmented Generation', 'Retrieval-Augmented Generation', 'retrievalaugmentedgeneration'),
    ('Retrieval-Augmented Generation', 'RAG', 'rag'),
    ('Vector Databases', 'Vector Databases', 'vectordatabases'),
    ('Vector Databases', 'Vector Store', 'vectorstore'),
    ('Vector Databases', 'Vector Search', 'vectorsearch'),
    ('Prompt Engineering', 'Prompt Engineering', 'promptengineering'),
    ('Large Language Models', 'Large Language Models', 'largelanguagemodels'),
    ('Large Language Models', 'LLM', 'llm'),
    ('Large Language Models', 'LLMs', 'llms'),
    ('Large Language Models', 'GenAI', 'genai'),
    ('Large Language Models', 'Generative AI', 'generativeai'),
    ('Machine Learning', 'Machine Learning', 'machinelearning'),
    ('Machine Learning', 'ML', 'ml'),
    ('TensorFlow', 'TensorFlow', 'tensorflow'),
    ('PyTorch', 'PyTorch', 'pytorch'),
    ('Hugging Face', 'Hugging Face', 'huggingface'),
    ('Ollama', 'Ollama', 'ollama'),
    ('Model Context Protocol', 'Model Context Protocol', 'modelcontextprotocol'),
    ('Model Context Protocol', 'MCP', 'mcp'),
    ('Microservices', 'Microservices', 'microservices'),
    ('Microservices', 'Microservice Architecture', 'microservicearchitecture'),
    ('Event-Driven Architecture', 'Event-Driven Architecture', 'eventdrivenarchitecture'),
    ('Event-Driven Architecture', 'EDA', 'eda'),
    ('Event-Driven Architecture', 'Event Driven', 'eventdriven'),
    ('Domain-Driven Design', 'Domain-Driven Design', 'domaindrivendesign'),
    ('Domain-Driven Design', 'DDD', 'ddd'),
    ('Hexagonal Architecture', 'Hexagonal Architecture', 'hexagonalarchitecture'),
    ('Hexagonal Architecture', 'Ports and Adapters', 'portsandadapters'),
    ('CQRS', 'CQRS', 'cqrs'),
    ('Event Sourcing', 'Event Sourcing', 'eventsourcing'),
    ('API Design', 'API Design', 'apidesign'),
    ('API Design', 'REST API Design', 'restapidesign'),
    ('Agile', 'Agile', 'agile'),
    ('Agile', 'Agile Methodologies', 'agilemethodologies'),
    ('Scrum', 'Scrum', 'scrum'),
    ('Kanban', 'Kanban', 'kanban'),
    ('Code Review', 'Code Review', 'codereview'),
    ('Code Review', 'Code Reviews', 'codereviews'),
    ('Pair Programming', 'Pair Programming', 'pairprogramming'),
    ('Clean Code', 'Clean Code', 'cleancode'),
    ('SOLID', 'SOLID', 'solid'),
    ('SOLID', 'SOLID Principles', 'solidprinciples'),
    ('Design Patterns', 'Design Patterns', 'designpatterns'),
    ('Refactoring', 'Refactoring', 'refactoring'),
    ('Distributed Systems', 'Distributed Systems', 'distributedsystems'),
    ('Concurrency', 'Concurrency', 'concurrency'),
    ('Concurrency', 'Multithreading', 'multithreading'),
    ('Concurrency', 'Concurrent Programming', 'concurrentprogramming'),
    ('Kotlin Coroutines', 'Kotlin Coroutines', 'kotlincoroutines'),
    ('Kotlin Coroutines', 'Coroutines', 'coroutines'),
    ('Reactive Programming', 'Reactive Programming', 'reactiveprogramming'),
    ('Reactive Programming', 'Reactor', 'reactor'),
    ('Reactive Programming', 'Project Reactor', 'projectreactor'),
    ('Reactive Programming', 'RxJava', 'rxjava'),
    ('Functional Programming', 'Functional Programming', 'functionalprogramming'),
    ('Functional Programming', 'FP', 'fp'),
    ('Object-Oriented Programming', 'Object-Oriented Programming', 'objectorientedprogramming'),
    ('Object-Oriented Programming', 'OOP', 'oop'),
    ('Performance Tuning', 'Performance Tuning', 'performancetuning'),
    ('Performance Tuning', 'Performance Optimization', 'performanceoptimization'),
    ('Performance Tuning', 'Profiling', 'profiling'),
    ('Application Security', 'Application Security', 'applicationsecurity'),
    ('Application Security', 'Security Best Practices', 'securitybestpractices'),
    ('Application Security', 'OWASP', 'owasp'),
    ('OAuth 2.0', 'OAuth 2.0', 'oauth20'),
    ('OAuth 2.0', 'OAuth2', 'oauth2'),
    ('OAuth 2.0', 'OAuth', 'oauth'),
    ('OpenID Connect', 'OpenID Connect', 'openidconnect'),
    ('OpenID Connect', 'OIDC', 'oidc'),
    ('JWT', 'JWT', 'jwt'),
    ('JWT', 'JSON Web Token', 'jsonwebtoken'),
    ('Observability', 'Observability', 'observability'),
    ('Observability', 'Monitoring', 'monitoring'),
    ('Observability', 'Logging', 'logging'),
    ('Observability', 'Tracing', 'tracing'),
    ('Caching', 'Caching', 'caching'),
    ('Caching', 'Cache', 'cache'),
    ('API Gateway', 'API Gateway', 'apigateway'),
    ('Load Balancing', 'Load Balancing', 'loadbalancing'),
    ('Scalability', 'Scalability', 'scalability'),
    ('Scalability', 'High Availability', 'highavailability'),
    ('Monolith', 'Monolith', 'monolith'),
    ('Monolith', 'Modular Monolith', 'modularmonolith'),
    ('Technical Documentation', 'Technical Documentation', 'technicaldocumentation'),
    ('Technical Documentation', 'Documentation', 'documentation'),
    ('IntelliJ IDEA', 'IntelliJ IDEA', 'intellijidea'),
    ('IntelliJ IDEA', 'IntelliJ', 'intellij'),
    ('Visual Studio Code', 'Visual Studio Code', 'visualstudiocode'),
    ('Visual Studio Code', 'VS Code', 'vscode'),
    ('Jira', 'Jira', 'jira'),
    ('Confluence', 'Confluence', 'confluence'),
    ('Postman', 'Postman', 'postman'),
    ('OpenAPI', 'OpenAPI', 'openapi'),
    ('OpenAPI', 'Swagger', 'swagger'),
    ('OpenAPI', 'OpenAPI Specification', 'openapispecification'),
    ('Figma', 'Figma', 'figma'),
    ('Communication', 'Communication', 'communication'),
    ('Communication', 'Communication Skills', 'communicationskills'),
    ('Teamwork', 'Teamwork', 'teamwork'),
    ('Teamwork', 'Collaboration', 'collaboration'),
    ('Teamwork', 'Team Player', 'teamplayer'),
    ('Mentoring', 'Mentoring', 'mentoring'),
    ('Mentoring', 'Coaching', 'coaching'),
    ('Leadership', 'Leadership', 'leadership'),
    ('Leadership', 'Tech Leadership', 'techleadership'),
    ('Leadership', 'Team Leadership', 'teamleadership'),
    ('Problem Solving', 'Problem Solving', 'problemsolving'),
    ('Problem Solving', 'Analytical Thinking', 'analyticalthinking'),
    ('Ownership', 'Ownership', 'ownership'),
    ('Ownership', 'Proactivity', 'proactivity'),
    ('Ownership', 'Self-Reliance', 'selfreliance'),
    ('Stakeholder Management', 'Stakeholder Management', 'stakeholdermanagement'),
    ('Time Management', 'Time Management', 'timemanagement'),
    ('Adaptability', 'Adaptability', 'adaptability'),
    ('Adaptability', 'Flexibility', 'flexibility')
) as v(skill_name, alias, normalized_alias)
join canonical_skill cs on cs.name = v.skill_name;

insert into skill_relation (from_skill_id, to_skill_id, kind)
select f.id, t.id, v.kind
from (values
    ('Spring Boot', 'Spring', 'IMPLIES'),
    ('Spring Security', 'Spring', 'IMPLIES'),
    ('Spring Data', 'Spring', 'IMPLIES'),
    ('Spring Batch', 'Spring', 'IMPLIES'),
    ('Spring Cloud', 'Spring', 'IMPLIES'),
    ('Spring WebFlux', 'Spring', 'IMPLIES'),
    ('Spring MVC', 'Spring', 'IMPLIES'),
    ('Spring Modulith', 'Spring', 'IMPLIES'),
    ('Spring AI', 'Spring', 'IMPLIES'),
    ('Spring Boot', 'Java', 'RELATED'),
    ('Java', 'Spring Boot', 'RELATED'),
    ('Kotlin', 'JVM', 'IMPLIES'),
    ('Java', 'JVM', 'IMPLIES'),
    ('Scala', 'JVM', 'IMPLIES'),
    ('Groovy', 'JVM', 'IMPLIES'),
    ('Clojure', 'JVM', 'IMPLIES'),
    ('Kotlin', 'Java', 'RELATED'),
    ('Java', 'Kotlin', 'RELATED'),
    ('Spring Data', 'JPA', 'RELATED'),
    ('JPA', 'Spring Data', 'RELATED'),
    ('Hibernate', 'JPA', 'IMPLIES'),
    ('Quarkus', 'Spring Boot', 'RELATED'),
    ('Spring Boot', 'Quarkus', 'RELATED'),
    ('Micronaut', 'Spring Boot', 'RELATED'),
    ('Spring Boot', 'Micronaut', 'RELATED'),
    ('Ktor', 'Spring Boot', 'RELATED'),
    ('Spring Boot', 'Ktor', 'RELATED'),
    ('Quarkus', 'Jakarta EE', 'RELATED'),
    ('Jakarta EE', 'Quarkus', 'RELATED'),
    ('TypeScript', 'JavaScript', 'IMPLIES'),
    ('Next.js', 'React', 'IMPLIES'),
    ('Redux', 'React', 'RELATED'),
    ('React', 'Redux', 'RELATED'),
    ('Astro', 'React', 'RELATED'),
    ('React', 'Astro', 'RELATED'),
    ('Svelte', 'React', 'RELATED'),
    ('React', 'Svelte', 'RELATED'),
    ('Vue.js', 'React', 'RELATED'),
    ('React', 'Vue.js', 'RELATED'),
    ('Angular', 'React', 'RELATED'),
    ('React', 'Angular', 'RELATED'),
    ('NestJS', 'Node.js', 'IMPLIES'),
    ('Express.js', 'Node.js', 'IMPLIES'),
    ('Sass', 'CSS', 'IMPLIES'),
    ('Tailwind CSS', 'CSS', 'IMPLIES'),
    ('MySQL', 'SQL', 'IMPLIES'),
    ('PostgreSQL', 'SQL', 'IMPLIES'),
    ('Oracle Database', 'SQL', 'IMPLIES'),
    ('SQL Server', 'SQL', 'IMPLIES'),
    ('MariaDB', 'MySQL', 'RELATED'),
    ('MySQL', 'MariaDB', 'RELATED'),
    ('PostgreSQL', 'MySQL', 'RELATED'),
    ('MySQL', 'PostgreSQL', 'RELATED'),
    ('Neon', 'PostgreSQL', 'IMPLIES'),
    ('pgvector', 'PostgreSQL', 'RELATED'),
    ('PostgreSQL', 'pgvector', 'RELATED'),
    ('Flyway', 'Liquibase', 'RELATED'),
    ('Liquibase', 'Flyway', 'RELATED'),
    ('Elasticsearch', 'ClickHouse', 'RELATED'),
    ('ClickHouse', 'Elasticsearch', 'RELATED'),
    ('Apache Kafka', 'RabbitMQ', 'RELATED'),
    ('RabbitMQ', 'Apache Kafka', 'RELATED'),
    ('Apache Pulsar', 'Apache Kafka', 'RELATED'),
    ('Apache Kafka', 'Apache Pulsar', 'RELATED'),
    ('ActiveMQ', 'RabbitMQ', 'RELATED'),
    ('RabbitMQ', 'ActiveMQ', 'RELATED'),
    ('Amazon SQS', 'RabbitMQ', 'RELATED'),
    ('RabbitMQ', 'Amazon SQS', 'RELATED'),
    ('Apache Kafka', 'Event-Driven Architecture', 'RELATED'),
    ('Event-Driven Architecture', 'Apache Kafka', 'RELATED'),
    ('gRPC', 'REST', 'RELATED'),
    ('REST', 'gRPC', 'RELATED'),
    ('GraphQL', 'REST', 'RELATED'),
    ('REST', 'GraphQL', 'RELATED'),
    ('Protocol Buffers', 'Apache Avro', 'RELATED'),
    ('Apache Avro', 'Protocol Buffers', 'RELATED'),
    ('AWS Lambda', 'AWS', 'IMPLIES'),
    ('Amazon S3', 'AWS', 'IMPLIES'),
    ('Amazon EC2', 'AWS', 'IMPLIES'),
    ('Amazon RDS', 'AWS', 'IMPLIES'),
    ('DynamoDB', 'AWS', 'IMPLIES'),
    ('Amazon SQS', 'AWS', 'IMPLIES'),
    ('Azure Functions', 'Microsoft Azure', 'IMPLIES'),
    ('AWS', 'Microsoft Azure', 'RELATED'),
    ('Microsoft Azure', 'AWS', 'RELATED'),
    ('AWS', 'Google Cloud Platform', 'RELATED'),
    ('Google Cloud Platform', 'AWS', 'RELATED'),
    ('Microsoft Azure', 'Google Cloud Platform', 'RELATED'),
    ('Google Cloud Platform', 'Microsoft Azure', 'RELATED'),
    ('AWS Lambda', 'Serverless', 'IMPLIES'),
    ('Azure Functions', 'Serverless', 'IMPLIES'),
    ('Kubernetes', 'Docker', 'RELATED'),
    ('Docker', 'Kubernetes', 'RELATED'),
    ('Helm', 'Kubernetes', 'IMPLIES'),
    ('ArgoCD', 'Kubernetes', 'RELATED'),
    ('Kubernetes', 'ArgoCD', 'RELATED'),
    ('Istio', 'Kubernetes', 'RELATED'),
    ('Kubernetes', 'Istio', 'RELATED'),
    ('Terraform', 'Ansible', 'RELATED'),
    ('Ansible', 'Terraform', 'RELATED'),
    ('GitHub Actions', 'CI/CD', 'IMPLIES'),
    ('GitLab CI', 'CI/CD', 'IMPLIES'),
    ('Jenkins', 'CI/CD', 'IMPLIES'),
    ('GitHub Actions', 'Jenkins', 'RELATED'),
    ('Jenkins', 'GitHub Actions', 'RELATED'),
    ('GitLab CI', 'Jenkins', 'RELATED'),
    ('Jenkins', 'GitLab CI', 'RELATED'),
    ('Grafana', 'Prometheus', 'RELATED'),
    ('Prometheus', 'Grafana', 'RELATED'),
    ('Datadog', 'Prometheus', 'RELATED'),
    ('Prometheus', 'Datadog', 'RELATED'),
    ('Prometheus', 'Observability', 'IMPLIES'),
    ('OpenTelemetry', 'Observability', 'IMPLIES'),
    ('ELK Stack', 'Observability', 'IMPLIES'),
    ('Micrometer', 'Observability', 'IMPLIES'),
    ('Kotest', 'JUnit', 'RELATED'),
    ('JUnit', 'Kotest', 'RELATED'),
    ('MockK', 'Mockito', 'RELATED'),
    ('Mockito', 'MockK', 'RELATED'),
    ('Kotest', 'Kotlin', 'RELATED'),
    ('Kotlin', 'Kotest', 'RELATED'),
    ('MockK', 'Kotlin', 'RELATED'),
    ('Kotlin', 'MockK', 'RELATED'),
    ('Cypress', 'Selenium', 'RELATED'),
    ('Selenium', 'Cypress', 'RELATED'),
    ('Playwright', 'Selenium', 'RELATED'),
    ('Selenium', 'Playwright', 'RELATED'),
    ('Playwright', 'Cypress', 'RELATED'),
    ('Cypress', 'Playwright', 'RELATED'),
    ('Gatling', 'JMeter', 'RELATED'),
    ('JMeter', 'Gatling', 'RELATED'),
    ('Test-Driven Development', 'Unit Testing', 'IMPLIES'),
    ('Testcontainers', 'Integration Testing', 'IMPLIES'),
    ('LangChain4j', 'LangChain', 'RELATED'),
    ('LangChain', 'LangChain4j', 'RELATED'),
    ('Spring AI', 'LangChain4j', 'RELATED'),
    ('LangChain4j', 'Spring AI', 'RELATED'),
    ('Spring AI', 'LangChain', 'RELATED'),
    ('LangChain', 'Spring AI', 'RELATED'),
    ('LangChain', 'Large Language Models', 'IMPLIES'),
    ('LangChain4j', 'Large Language Models', 'IMPLIES'),
    ('OpenAI API', 'Large Language Models', 'IMPLIES'),
    ('Retrieval-Augmented Generation', 'Vector Databases', 'RELATED'),
    ('Vector Databases', 'Retrieval-Augmented Generation', 'RELATED'),
    ('Retrieval-Augmented Generation', 'Large Language Models', 'IMPLIES'),
    ('Prompt Engineering', 'Large Language Models', 'IMPLIES'),
    ('Ollama', 'Large Language Models', 'IMPLIES'),
    ('pgvector', 'Vector Databases', 'IMPLIES'),
    ('PyTorch', 'TensorFlow', 'RELATED'),
    ('TensorFlow', 'PyTorch', 'RELATED'),
    ('PyTorch', 'Machine Learning', 'IMPLIES'),
    ('TensorFlow', 'Machine Learning', 'IMPLIES'),
    ('Microservices', 'Distributed Systems', 'IMPLIES'),
    ('Event Sourcing', 'CQRS', 'RELATED'),
    ('CQRS', 'Event Sourcing', 'RELATED'),
    ('CQRS', 'Domain-Driven Design', 'RELATED'),
    ('Domain-Driven Design', 'CQRS', 'RELATED'),
    ('Hexagonal Architecture', 'Domain-Driven Design', 'RELATED'),
    ('Domain-Driven Design', 'Hexagonal Architecture', 'RELATED'),
    ('Monolith', 'Microservices', 'RELATED'),
    ('Microservices', 'Monolith', 'RELATED'),
    ('Scrum', 'Agile', 'IMPLIES'),
    ('Kanban', 'Agile', 'IMPLIES'),
    ('Kotlin Coroutines', 'Concurrency', 'IMPLIES'),
    ('Kotlin Coroutines', 'Kotlin', 'RELATED'),
    ('Kotlin', 'Kotlin Coroutines', 'RELATED'),
    ('Reactive Programming', 'Concurrency', 'RELATED'),
    ('Concurrency', 'Reactive Programming', 'RELATED'),
    ('Spring WebFlux', 'Reactive Programming', 'IMPLIES'),
    ('OAuth 2.0', 'Application Security', 'RELATED'),
    ('Application Security', 'OAuth 2.0', 'RELATED'),
    ('OpenID Connect', 'OAuth 2.0', 'IMPLIES'),
    ('JWT', 'OAuth 2.0', 'RELATED'),
    ('OAuth 2.0', 'JWT', 'RELATED'),
    ('Spring Security', 'Application Security', 'IMPLIES'),
    ('SOLID', 'Clean Code', 'RELATED'),
    ('Clean Code', 'SOLID', 'RELATED'),
    ('Design Patterns', 'Clean Code', 'RELATED'),
    ('Clean Code', 'Design Patterns', 'RELATED'),
    ('Redis', 'Caching', 'IMPLIES'),
    ('Nginx', 'Load Balancing', 'IMPLIES'),
    ('API Gateway', 'Load Balancing', 'RELATED'),
    ('Load Balancing', 'API Gateway', 'RELATED'),
    ('Mentoring', 'Leadership', 'RELATED'),
    ('Leadership', 'Mentoring', 'RELATED'),
    ('Pair Programming', 'Mentoring', 'RELATED'),
    ('Mentoring', 'Pair Programming', 'RELATED'),
    ('Code Review', 'Teamwork', 'RELATED'),
    ('Teamwork', 'Code Review', 'RELATED'),
    ('Data Modeling', 'Database Design', 'RELATED'),
    ('Database Design', 'Data Modeling', 'RELATED'),
    ('Maven', 'Gradle', 'RELATED'),
    ('Gradle', 'Maven', 'RELATED'),
    ('Thymeleaf', 'Spring', 'RELATED'),
    ('Spring', 'Thymeleaf', 'RELATED'),
    ('jOOQ', 'SQL', 'RELATED'),
    ('SQL', 'jOOQ', 'RELATED'),
    ('MyBatis', 'SQL', 'RELATED'),
    ('SQL', 'MyBatis', 'RELATED'),
    ('Vert.x', 'Reactive Programming', 'RELATED'),
    ('Reactive Programming', 'Vert.x', 'RELATED')
) as v(from_name, to_name, kind)
join canonical_skill f on f.name = v.from_name
join canonical_skill t on t.name = v.to_name
on conflict do nothing;
